apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zf8c3bq1y-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zf8c3bq1y-go 
  name: zf8c3bq1y-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zf8c3bq1y-go 
