apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: zf8c3bq1y-go 
  janus-idp.io/tekton: zf8c3bq1y-go
  backstage.io/kubernetes-id: zf8c3bq1y-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zf8c3bq1y-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml